### ISSUE TITLE
copy(A::Toeplitz) returns a regular Array

### ISSUE THREAD

**Issue by BenjaminRemez** [JuliaLinearAlgebra/ToeplitzMatrices.jl#69]
Calling `copy(A)` for `A::Toeplitz` falls back to `copy(AbstractArray)`, and then returns a dense, populated `Array`, instead of a new `Toeplitz`. 

(This has an interesting side effect: it allows `LinearAlgebra.det(A)` to run successfully, since a copy during that routine causes a "densification" of A, whereas `det(C::Circulant)` fails, as `Circulant` implements a specialized copy method. This might we a separate wider issue to resolve.)

**Comment by putianyi889** [comment]
should have been fixed by #76

**Comment by jishnub** [comment]
Closing, as it's fixed
